
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { z } from "zod";

const directUrl = z.string().trim().min(1).url().safeParse(process.env.DIRECT_URL);

if (!directUrl.success) {
  throw new Error("Invalid or missing environment variable: DIRECT_URL");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: directUrl.data,
  },
});
